### ISSUE TITLE
Lower the command limit on Soul Silver

### ISSUE THREAD

**Issue by Emily-Husky** [YouTubePlays/YouTubePlaysBot#4]
Soul Silver has a lot more viewers than any other stream has had the last few months, so the command limit of 20 per message is way too high, especially now without the spam filter. At one point we were waiting for the commands of 3 minutes earlier. I'd suggest taking the limit on that stream down to either 5 or 10. (I prefer 10, the mods prefer 5)

**Comment by YouTubePlays** [comment]
Done
